version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r backend/requirements.txt

  build:
    commands:
      - echo "Build phase complete"

artifacts:
  base-directory: backend
  files:
    - '**/*'
